---
transformations:
  - id: '0'
    camera: 'tapo_camera_kitchen'
    matrix:
      - [0.866, -0.5, 0.0, 1.0]
      - [0.5, 0.866, 0.0, 2.0]
      - [0.0, 0.0, 1.0, 3.0]
      - [0.0, 0.0, 0.0, 1.0]
  - id: '1'
    camera: 'tapo_camera_living'
    matrix:
      - [1.0, 0.0, 0.0, 0.0]
      - [0.0, 1.0, 0.0, 0.0]
      - [0.0, 0.0, 1.0, 0.0]
      - [0.0, 0.0, 0.0, 1.0]
  - id: '2'
    camera: 'tapo_camera_dining'
    matrix:
      - [ 0.866, -0.5, 0.0, 1.0 ]
      - [ 0.5, 0.866, 0.0, 2.0 ]
      - [ 0.0, 0.0, 1.0, 3.0 ]
      - [ 0.0, 0.0, 0.0, 1.0 ]
  - id: '3'
    camera: 'tapo_camera_bedroom'
    matrix:
      - [ 1.0, 0.0, 0.0, 0.0 ]
      - [ 0.0, 1.0, 0.0, 0.0 ]
      - [ 0.0, 0.0, 1.0, 0.0 ]
      - [ 0.0, 0.0, 0.0, 1.0 ]