---
transformations:
  - id: 'matrix1'
    matrix:
      - [0.866, -0.5, 0.0, 1.0]
      - [0.5, 0.866, 0.0, 2.0]
      - [0.0, 0.0, 1.0, 3.0]
      - [0.0, 0.0, 0.0, 1.0]
  - id: 'matrix2'
    matrix:
      - [1.0, 0.0, 0.0, 0.0]
      - [0.0, 1.0, 0.0, 0.0]
      - [0.0, 0.0, 1.0, 0.0]
      - [0.0, 0.0, 0.0, 1.0]